# Generated by Django 4.2.6 on 2023-11-20 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50, verbose_name='Название')),
                ('anouncement', models.TextField(max_length=250, verbose_name='Аннотация')),
                ('text', models.TextField(verbose_name='Текст новости')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Дата публикации')),
                ('category', models.CharField(choices=[('E', 'Economics'), ('S', 'Science'), ('IT', 'IT')], max_length=20, verbose_name='Категории')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['title', 'date'],
            },
        ),
    ]
