# Generated by Django 4.2.6 on 2023-12-02 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('news', '0004_tag_article_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.account'),
        ),
    ]
