# Generated by Django 4.2.6 on 2023-12-22 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_viewcount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='account',
        ),
    ]
