# Generated by Django 4.2.6 on 2023-12-21 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_account_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='nickname',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
